### PR TITLE
chore(pages): component content cleanup

### PR DESCRIPTION
**Pull request by kennylam**
### Related Ticket(s)

https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/7041
https://github.com/IBM/beacon-for-ibm-dotcom/issues/34

### Description

**Waiting for #114 to merge**

This updates all test page content to match current React Storybook and Codesandbox examples. Also changes example page names (URLs) to be more generic.

Note: Many component style fixes are in `v1.25.0` and will not be reflected until `package.json` is updated. Current application is still using `v1.24.0`.

### Changelog

**New**

- FPO images

**Changed**

- update all page content to match latest React Storybook/Codesandbox
- `learn.js`, `solutions.js`, `services.js` ⭢ `example-page-a.js`, `example-page-b.js`, `example-page-c.js` respectively

**Removed**

- `node-fetch`

### CODE REVIEW

**Comment by jeffchew** [comment]
Thanks @kennylam for the cleanup!

Not sure if I see updated e2e tests, can you update so they point to the new pages?

**Comment by kennylam** [comment]
> Not sure if I see updated e2e tests, can you update so they point to the new pages?

@jeffchew Oh good call, I didn't realize they were added to this app.

**Comment by jeffchew** [comment]
@kennylam there's still some missing imagery, is that supposed to be covered in this PR?

image

**Comment by kennylam** [comment]
> @kennylam there's still some missing imagery, is that supposed to be covered in this PR?

Strange, none of the images are coming through in the deploy preview. But they're all loading locally no problems.

**Review by jeffchew — APPROVED** [review]
LGTM!

**Pull request merged**
