### PR TITLE
feat(e2e): adding example page a e2e tests

### PR DESCRIPTION
**Pull request by IgnacioBecerra**
### Related Ticket(s)
[#7843
](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/7843)

### Description
Adding the e2e tests for the Example Page A, using some helper functions from our main repo.

### Changelog

**New**

- e2e tests for example page a

### CODE REVIEW

**Comment by jeffchew** [comment]
Looking at the logs, one of the tests failed:

image

**Comment by IgnacioBecerra** [comment]
Hmm it passes locally, let me see what's up with this one

**Comment by IgnacioBecerra** [comment]
Example page A page -- should load footer and clickable content (failed)
Seems like cypress is rendering "Follow IBM" links twice, resulting in 41 instead of the expected 38. Not sure what's causing or how to mitigate this, should we comment out the test for now?

**Review by jeffchew — APPROVED** [review]
LGTM!

**Comment by jeffchew** [comment]
@IgnacioBecerra looks like the tests are failing for this:

image

**Pull request merged**
